<TwoLineAvatarListItem>
    IconLeftWidget:
#        icon: root.icon





<AchScreen>
    name: "ach"
    #Image:
    #    source: 'images/rh.jpg'
    #    size: self.width,self.height
    BoxLayout:
        id: graphs2
        orientation: "vertical"
        
        MDTopAppBar:
            #title: "Settings"
            height: app.mheight
            left_action_items: [['chevron-left', lambda screen: app.change_screen('mainmenu','left'),'home'],["check-bold", lambda x: app.check_ach(),'check ach']]
            right_action_items: [["refresh", lambda x: app.ach_reset(),'reset ach'],["counter", lambda x: app.ach_top(0),'reset ach']]
        MDBoxLayout:
            orientation: 'vertical'
            adaptive_height: True
            adaptive_size: True
            #height: app.mheight
            #size_hint: .1,.1
            
            MDBoxLayout:
                #orientation: 'horizontal'
                adaptive_height: True
                adaptive_size: True
                #height: app.mheight
                #size_hint: .1,.1
                
                MDButton:
                    text: 'All'
                    id: alld
                    #size_hint: .3,None
                    #height: app.mheight
                    #md_bg_color: app.theme_cls.primary_light
                    #padding:10
                    on_press:(app.trophys('all'))
                MDButton:
                    text: 'Done'
                    id: doned
                    #size_hint: .3,None
                    #height: app.mheight
                    #md_bg_color: app.theme_cls.primary_light
                    #padding:10
                    on_press:(app.trophys('done'))
                MDButton:
                    text: 'Not Yet Done'
                    id: ndoned
                    #size_hint: .3,None
                    #height: app.mheight
                    #md_bg_color: app.theme_cls.primary_light
                    #padding:10
                    on_press:(app.trophys('notdone'))


            MDListItem:
                icon: 'palette'
                text: "Points=0"
                id: ach_points
                on_press:(app.ach_top(0))

        ScrollView:


            MDList:
                id: ach_id
