<backupgooglescreen>
    #:import Clipboard kivy.core.clipboard.Clipboard
    #:import Snackbar kivymd.uix.snackbar.Snackbar
    name: "backupgoogle"
    #Image:
    #    source: 'images/rh.jpg'
    #    size: self.width,self.height
    BoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            #title: "Settings"
            height: app.mheight
            left_action_items: [['chevron-left', lambda screen: app.change_screen('today','left'),'home']]
        ScrollView:


            MDList:
                ThreeLineAvatarIconListItem:
                    text: 'Cloud Backup'
                    id:last_backup
                    secondary_text: 'Last Backup:'
                    on_release: 
                        #toast('starting backup')
                        app.do_backups()
                    IconLeftWidget:
                        icon: "cloud-upload"

                ThreeLineAvatarIconListItem:
                    text: 'Cloud Restore'
                    id:last_restore

                    secondary_text: 'None'
                    on_release: app.do_restore(self.secondary_text)

                    YourContainer:
                        MDButton:
                            id: button4
                            #padding: [15, 15]

                            #width: 5
                            text: "click"
                            pos_hint: {'center_x': .5, 'center_y': .35}
                            values: app.find_gbackups()
                            items: app.find_gbackups()
                            #id: noise
                            on_release: app.choose_drop(app.find_gbackups(),'name')




                    IconLeftWidget:
                        icon: "cloud-download"
                MDListItem:
                    text: 'Auto Backup'
                    YourContainer:
                        MDSwitch:
                            widget_style: "ios"
                            id: usegoogle
                            active: app.check_att("usegoogle")
                            on_active: app.updatetext("usegoogle")
                    IconLeftWidget:
                        icon: "google-cloud"

                MDListItem:
                    text: 'Backup Shows'
                    YourContainer:
                        MDSwitch:
                            widget_style: "ios"
                            id: backup_shows
                            active: app.check_att("backup_shows")
                            on_active: app.updatetext("backup_shows")
                    IconLeftWidget:
                        icon: "google-cloud"
                MDListItem:
                    text: 'Backup Config'
                    YourContainer:
                        MDSwitch:
                            widget_style: "ios"
                            id: backup_config
                            active: app.check_att("backup_config")
                            on_active: app.updatetext("backup_config")
                    IconLeftWidget:
                        icon: "google-cloud"
                MDListItem:
                    text: 'Backup Paychecks'
                    YourContainer:
                        MDSwitch:
                            widget_style: "ios"
                            id: backup_checks
                            active: app.check_att("backup_checks")
                            on_active: app.updatetext("backup_checks")
                    IconLeftWidget:
                        icon: "google-cloud"
