<TwoLineAvatarListItem>
    IconLeftWidget:
#        icon: root.icon
<HistoryItem>
    canvas.before:
        Color:
            rgba: app.theme_cls.accent_color
    size_hint_y: None
    height:dp(150)

    MDCardSwipeLayerBox:

        MDIconButton:
            icon: "trash-can"
            pos_hint: {"center_y": .5}
            #on_release: app.on_swipe_complete(root)
            focus_behavior: True

    MDCardSwipeFrontBox:
        #border_radius: 5
        #radius: 10
        #elevation: 15
        #focus_behavior: True

        #OneLineListItem:
        id: mdswipefrontbox
        
        MDCard:
        #SmartTileWithLabel:
            source: 'images/rh.jpg'
            border_radius: app.bradius
            radius: app.radius
            #focus_behavior: True
            ripple_behavior: True
            #md_bg_color: app.theme_cls.accent_color
            md_bg_color: app.theme_cls.primary_light if int((root.text[-1:]))%2==1 else app.theme_cls.primary_dark
            
            on_release: 
                #app.change_screen('info','up')
                #root.click(self)

                
            #on_release: app.click(self)
            #on_release: root.click(self)
            theme_text_color: "Primary"
            id: idmdcard
            #border_radius:[0,5,0,5]
            #radius:[0,5,0,5]
            #elevation: 15
            padding: 5
            #text:'lol'
            


            MDLabel:
                id: idmdlabel
                
                
                #font_name: app.mfont
                markup: True
                theme_text_color: "Primary"
                text: root.text
                #text: (root.text[-1:])
            #_no_ripple_effect: True



<ChatScreen>
    name: "chat"
    canvas.before:
        Color:
            rgba: app.theme_cls.accent_color
    Image:
        source: 'images/rh.jpg'
        size: self.width,self.height

    



    MDBoxLayout:
        id: graphs2
        orientation: "vertical"
        
        MDTopAppBar:
            #title: "Settings"
            id:toolbar2
            height: app.mheight
        #    type: "bottom"
            left_action_items: [['chevron-left', lambda screen: app.change_screen('today','left'),'home']]
            #right_action_items: [["refresh", lambda x: app.ach_reset(),'reset ach'],["counter", lambda x: app.ach_top(0),'reset ach']]
        BoxLayout:
            id: history_list2
            orientation: "vertical"
            #height: sv.height

            MDCard:
                orientation: "vertical"
                size_hint: .95, .5
                height: show_info.height
                focus_behavior: True
                ripple_behavior: True
                pos_hint: {"center_x": .5, "center_y": .5}
                ThreeLineListItem:
                    id:show_info
            MDCard:
                orientation: "vertical"
                size_hint: .95, None
                height: history_list2.height-toolbar2.height-textfield.height-(show_info.height/2)
                #focus_behavior: True
                #ripple_behavior: True
                pos_hint: {"center_x": .5, "center_y": .5}
                on_release: app.pop_new(0)

                ScrollView:
                    id: sv
                    scroll_y:0
                    scroll_x:0
                    spacing: app.cspacing

                    
                    MDList:
                        
                        spacing: app.cspacing
                        padding: app.cpadding,app.cpadding
                        id: history_list
            MDCard:
                orientation: "vertical"
                size_hint: .95, None
                height: show_info.height 
                focus_behavior: True
                ripple_behavior: True
                pos_hint: {"center_x": .5, "center_y": .5}
                BoxLayout:
                    id: history_list4
                    orientation: "horizontal"
                    MDTextField:
                        id:textfield
                    MDButton:
                        text:"Send!"
                        on_release:app.add_message_to_chat(textfield.text)