<editShowscreen>

    name: "editShow"
    #FitImage:
    #    #source: 'images/rh.jpg'
    #    id: pic
    #    source: app.get_wall("today")
    #    size: self.width,self.height
    BoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            #title: "Settings"
        #    height: app.mheight
            #left_action_items: [['chevron-left', lambda screen: app.change_screen('today','left'),'home']]


            MDTopAppBarLeadingButtonContainer:
    
                MDActionTopAppBarButton:
                    icon: "chevron-left"
                    on_release: app.root.pop()
                    pos_hint:{"center_x": 0.5, "center_y": 0.5}
        ScrollView:
            #id: history_view

            
            MDList:
                spacing: app.cspacing/2
                padding: app.cpadding/2,app.cpadding/2
                #bg_color:app.theme_cls.bg_dark
                #id: archive
                id: show5
                MDListItem:
                    id: show3
                    #bg_color: app.theme_cls.bg_dark
                    #id:show
                    text:'bla'
                    MDListItemSupportingText:
                        id:show
                    MDListItemSupportingText:
                        id:show2



                    MDListItemLeadingIcon:
                        icon:"calendar-star"
                MDListItem:
                    #bg_color: app.theme_cls.bg_dark
                    
                    id: lunches

                    MDListItemSupportingText:
                        text: "Hour Unpaid Lunches"
                    MDButton:
                        id: button4
                        padding: [15, 15]

                        #width: 5
                        text: "3"
                        trailing_text:'wat'
                        pos_hint: {'center_x': .5, 'center_y': .5}
                        values: app.lunches
                        items: app.lunches
                        id: button4
                        on_release: app.open_drop_item_menu(app.lunches,'lunches')
                        size_hint:app.right_hint
                        width:app.right_width
                        MDButtonText:
                            id: button4
                    MDListItemLeadingIcon:
                        icon: "food"

                MDListItem:
                    #bg_color: app.theme_cls.bg_dark
                    
                    id: ota

                    MDButton:
                        padding: [15, 15]
                        size_hint:app.right_hint
                        width:app.right_width

                        #width: 5
                        
                        pos_hint: {'center_x': .5, 'center_y': .5}
                        #values: app.oth
                        items: app.oth
                        id: button5
                        on_release: app.open_drop_item_menu(app.oth,'oth')
                        text: "8"
                        MDButtonText:
                            id: button5
                    MDListItemSupportingText:
                        text: "OverTime After"
                            
                    MDListItemLeadingIcon:
                        icon: "one-up"

                MDListItem:
                    #bg_color: app.theme_cls.bg_dark
                    id: endtime
                    MDListItemLeadingIcon:
                        icon: "clock"


                    MDButton:
                        text:"Time"
                        #id:newhours
                        padding: [15, 15]
                        pos_hint: {'center_x': .5, 'center_y': .5}
                        size_hint:app.right_hint
                        width:app.right_width
                        on_release: app.show_time_picker_vertical()
                        MDButtonText:  
                            id:newhours

                    MDListItemSupportingText:  
                        text: "Time Out"          

                MDListItem:
                    #bg_color: app.theme_cls.bg_dark
                    
                    id: endtime
                    MDListItemLeadingIcon:
                        icon: "update"


                    MDButton:
                        text:"Time"
                        
                        #id:newhoursplus
                        #padding: [15, 15]
                        #pos_hint: {'center_x': .5, 'center_y': .5}
                        #size_hint:app.right_hint
                        #width:app.right_width
                        #size_hint:None,None
                        #width:app.right_width*1.5
                        #size_hint:app.right_hint
                        
                        #on_release: app.show_time_picker("end_time")
                        MDButtonText:
                            id: newhoursplus
                            text:'wow'
                    MDListItemSupportingText:
                        text: "Total Hours"

                MDListItem:
                    #bg_color: app.theme_cls.bg_dark
                    #text: "Rate"
                    id: rat
                    #on_release: app.tokast('wow')
                    on_release: app.set_rate()
                    MDListItemLeadingIcon:
                        icon: "cash"

                    #MDTextField:
                    TextInput:
                        color_mode: 'accent'
                        #text:"28.5"
                        #padding: [15, 15]
                        pos_hint: {'center_x': .5, 'center_y': .5}
                        #pos_hint: {.9: .5}
                        size_hint:.3,.8
                        
                        id:rate
                        #size_hint:app.right_hint
                        #width:app.right_width
                        #id:newhours
                    MDListItemSupportingText:
                        text: "Rate"
                            
                MDListItem:
                    #bg_color: app.theme_cls.bg_dark
                    
                    id: rate1
                    #on_release: app.tokast('wow')
                    MDListItemLeadingIcon:
                        icon: "cash-multiple"

                    MDListItemSupportingText:
                        text: "Earnings"
                    MDButton:
                        #text:"28.5"
                        #padding: [15, 15]
                        #pos_hint: {'center_x': .5, 'center_y': .5}
                        MDButtonText
                            id:earningsl
                        #size_hint:app.right_hint
                        #width:app.right_width+200
                        #id:newhours
                        #on_release: app.show_time_picker()



                MDTextField:

                    id: user_notes
                    valign: 'middle'
                    hint_text:'Notes'
                    halign: 'left'
                    font_size: dp(16)
                    multiline: True
                    size_hint: 1, None
                    height: dp(70)
                    #height: scrlv.height
                    text:''
                    background_color: app.theme_cls.backgroundColor
                    hint_text_color:app.theme_cls.onBackgroundColor
                    text_color:app.theme_cls.onBackgroundColor
                    #foreground_color:app.theme_cls.opposite_bg_dark

                BoxLayout:
                    pos_hint: {"center_x": .8, "center_y": .5}
                    orientation: "horizontal"
                    height: dp(50)
                    #spacing: app.cspacing/2
                    #padding: dp(100),dp(100)
                    size_hint: 1, None
                    width:update.width*5
                    
                    MDButton:
                        
                        id:update
                        spacing: app.cspacing/2
                        on_release: app.update_show()
                        MDButtonText:
                            text:"Update"
                    MDButton:
                        text:"Hide"
                        spacing: app.cspacing/2
                        on_release: app.hide_show()
                        MDButtonText:
                            text:"Hide"
                    MDButton:
                        text:"Delete"
                        spacing: app.cspacing/2
                        on_release: app.delete_show()
                        MDButtonText:
                            text:"Delete"
