<CustomOneLineListItem@MDBoxLayout>:
    text:''
    #adaptive_width: True
    width:200
    id:container
    MDIconButton:
        icon: "minus"

    MDIconButton:
        icon: "plus"


<MDListItem2>
    text: "One-line item with avatar"
    on_size:
        self.ids._right_container.width = container.width
        self.ids._right_container.x = container.width

    IconLeftWidget:
        icon: "cog"

    YourContainer:
        id: container

        MDIconButton:
            icon: "minus"

        MDIconButton:
            icon: "plus"
    
<graphOrderscreen>

    name: "graphOrder"
    #BoxLayout:
    #    MDTopAppBar:
    #        left_action_items: [['chevron-left', lambda screen: app.change_screen('today','left'),'home']]
    #       

    FitImage:
        #source: 'images/rh.jpg'
        #id: pic
        #source: app.get_wall("today")
        #size: self.width,self.height

    


    #MDBottomNavigation:

    #    MDBottomNavigationItem:
    #        name: "screen 1"
    #    MDBottomNavigationItem:
    #        name: "screen 1"
    #    MDBottomNavigationItem:
    #        name: "screen 1"



    MDBoxLayout:
        id: graphs2
        orientation: "vertical"
        
        MDTopAppBar:
            #title: "Settings"
            height: app.mheight
        #    type: "bottom"

            left_action_items: [['chevron-left', lambda screen: app.change_screen('newstats','left'),'home']]

            right_action_items: [['reload-alert', lambda screen: app.do_graphOrder(),'order']]
        ScrollView:
            id: boxes
            MDGridLayout:
                bg_color:app.theme_cls.primary_dark
                cols: 1
                id: box
                adaptive_height: True
                padding: dp(10), dp(10)
                spacing: dp(4)
                border_radius: 15
                radius: app.cradius
                #text_color:app.theme_cls.primary_color
                MDCard: