#:import dp kivy.metrics.dp

<LoginScreen>:
    name: "login"
    

    MDBoxLayout:
        orientation: "vertical"

        MDTopAppBar:
            type: "small"

            #MDTopAppBarHeadlineText:
            #    text: "Sign In"

        MDBoxLayout:
            orientation: "vertical"

            padding: dp(24)
            spacing: dp(20)

            Widget:
                size_hint_y: .15

            MDIcon:
                icon: "calendar-account"
                halign: "center"
                font_size: dp(72)

            MDLabel:
                text: "!!Schedulara"

                halign: "center"

                font_style: "Display"
                role: "small"

            MDLabel:
                text: "Secure sign-in via Dispatch"

                halign: "center"

                theme_text_color: "Secondary"

            Widget:
                size_hint_y: None
                height: dp(16)

            MDCard:
                style: "outlined"

                radius: [18]

                size_hint_y: None
                height: dp(420)

                MDBoxLayout:
                    orientation: "vertical"

                    padding: dp(16)

                    spacing: dp(12)

                    MDBoxLayout:
                        id: webview_placeholder
                        md_bg_color:
                            app.theme_cls.surfaceContainerHighestColor

                        radius: [12]

                        canvas.before:
                            Color:
                                rgba: self.md_bg_color

                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [12]

                        MDLabel:
                            text: "Loading Dispatch Portal..."

                            halign: "center"

                            theme_text_color: "Secondary"

            Widget:
    MDButton:
        id: done_button

        style: "text"

        pos_hint: {"right": 1, "top": 1}

        opacity: 1

        on_release:
            app.close_webview()

        MDButtonText:
            text: "Done"