


<newsearchScreen>
    name: "newsarch"
    FitImage:
        source: 'images/rh.jpg'
        id: pic
        source: app.get_wall("today")
        size: self.width,self.height
    

    BoxLayout:

        orientation: "vertical"
        MDTopAppBar:
            height: app.mheight
            left_action_items: [['chevron-left', lambda screen: app.change_screen('today','left'),'home']]
        MDBoxLayout:
            #orientation: 'horizontal'
            size_hint: 1,None
            height:dp(42)
            MDButton:
                text: 'Date'
                id: timeIn

                on_press:(app.do_payperiod_trim('timeIn','search'))
            MDButton:
                text: '$$$'

                id: Total
                on_press:app.do_payperiod_trim('Total','search')
            MDButton:
                text: 'Hours'

                id: tot_hours
                on_press:
                    app.spinner_toggle()
                    app.do_payperiod_trim('tot_hours','search')
                    app.spinner_toggle()
                    #(app.set_pp('custom'))
            #MDIconButton:
            MDFloatingActionButton:
                #height: 1
                md_bg_color:app.theme_cls.primary_light
                #text: app.check_var(app.rreverse)
                #text_size:5
                #font_size: "18sp"
                id: sall
                line_color:(0, 0, 0, 0)
                on_press:
                    app.do_payperiod_trim(app.sort_search,'search')

        MDBoxLayout:
            #orientation: 'horizontal'
            size_hint: 1,None
            #height: app.mheight+10
            width: 1000
            #height:dp(42)
            height:dp(0)

            

            #MDButton:
                #text: 'YTD'
                #id: YTD

                #on_press:(app.do_payperiod_f('YTD'))
            #MDButton:
                #text: 'Year'
                #id: Year

                #on_press:(app.do_payperiod_f('Year'))
            #MDButton:
                #text: 'All'
                #id: All

                #on_press:(app.do_payperiod_f('All'))
            #MDButton:
                #text: 'Custom'
                #id: Custom

                #on_press:
                    #(app.show_date_picker())
        
        #MDBoxLayout:
        #    orientation: 'horizontal'
        #    size_hint: 1,None
        #    height:dp(42)
        #    MDButton:
        #        text: 'All'
        #        id: dstart

        #    MDButton:
        #        text: 'All'#

        #        id: dend
            
        ScrollView:
            #id: history_view

            
            MDList:
            
                
                spacing: app.cspacing/2
                padding: app.cpadding/2,app.cpadding/2
                bg_color:app.theme_cls.primary_light
                id: search_list
