<MyAKOnboardingItem@AKOnboardingItem>
    source: ""
    text: ""
    title: ""
    MDFloatLayout:
        Image:
            source: root.source
            pos_hint: {"center_x": .5, "y": .6}
            size_hint: .4, .3
        MDTopAppBar:
            height: app.mheight
            left_action_items: [['chevron-left', lambda screen: app.change_screen('today','left'),'home']]
        MDBoxLayout:
            orientation: "vertical"
            padding: dp(10)
            adaptive_height: True
            pos_hint: {"center_x": .5, "top": .5}
            spacing: dp(20)
            size_hint_x: .7
            canvas.before:
                Color:
                    rgba: app.theme_cls.primary_dark
                RoundedRectangle:
                    pos: self.pos
                    size: self.size

            MDLabel:
                text: root.title
                bold: True
                size_hint_y: None
                height: self.texture_size[1]
                theme_text_color: "Primary"
                font_style: "H6"
                halign: "center"
                valign: "center"
            MDLabel:
                size_hint_y: None
                height: self.texture_size[1]
                theme_text_color: "Primary"
                font_style: "Body1"
                halign: "center"
                valign: "center"
                text: root.text


<onboardingscreen2>
    name: "onboarding"
    BoxLayout:

        
        MDTopbar:
            #title: "Settings"
            height: app.mheight
            left_action_items: [['chevron-left', lambda screen: app.change_screen('today','left'),'home']]
        MDBoxLayout:
            orientation: "vertical"
            spacing: dp(10)
            AKOnboarding:
                id: boarding
                #on_finish: root.finish_callback()
                circles_size: dp(15)
                MyAKOnboardingItem:
                    source: "assets/slide_one_img.png"
                    text: "Lorem Ipsum is simply dummy text of the logging.infoing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown logging.infoer took a galley of type and scrambled it to make a type specimen book"
                    title:"What is Lorem Ipsum?"
                MyAKOnboardingItem:
                    source: "assets/slide_one_img.png"
                    text: "Lorem Ipsum is simply dummy text of the logging.infoing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown logging.infoer took a galley of type and scrambled it to make a type specimen book"
                    title:"What is Lorem Ipsum?"

    




