<today2screen>
    #:import Clipboard kivy.core.clipboard.Clipboard
    #:import Snackbar kivymd.uix.snackbar.Snackbar
    name: "today2"
    Image:
        source: 'images/rh.jpg'
        size: self.width,self.height
    BoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            #title: "Settings"
            height: app.mheight
            left_action_items: [['chevron-left', lambda screen: app.change_screen('today','left'),'home']]