
#:import dp kivy.metrics.dp

<TodayScreen>:
    name: "today"
    MDScrollView:
        

        MDBoxLayout:
            adaptive_height: True
            spacing: dp(6)
            #padding: dp(36)
            orientation: "vertical"
    

            Widget:
                size_hint_y: None
                #height: self.theme_cls.device_safe_area.top
                height:dp(12)
            
            


            MDGridLayout:
                cols: 2
                spacing: dp(12)
                #padding : dp(12)
                adaptive_height: True

                StatCard:
                    id: update_card
                    icon: "update"
                    value: "8 "
                    title: "Hours ago"
                    subtitle: "Tap to update"
                    on_release: app.update()

                    icon_color: app.theme_cls.secondaryColor
                    circle_color:
                        app.theme_cls.secondaryColor[0], \
                        app.theme_cls.secondaryColor[1], \
                        app.theme_cls.secondaryColor[2], \
                        .12
            
                StatCard:
                    icon: "check-circle"
                    id: confirmed_card
                    value: "12"
                    title: "Confirmed"
                    subtitle: "0 Pending"
                    on_release: app.check_confirm()

                    icon_color: app.theme_cls.secondaryColor
                    circle_color:
                        app.theme_cls.secondaryColor[0], \
                        app.theme_cls.secondaryColor[1], \
                        app.theme_cls.secondaryColor[2], \
                        .12
            






            MDLabel:
                text: "UP NEXT"
                adaptive_height: True

                font_style: "Label"
                role: "large"

                theme_text_color: "Secondary"

                bold: True

                padding: dp(8), 0
            ShowCard:
                id: show_card_1
                #show: "Summer Walker"

                class_color: (.20,.55,.95,1)
                show_class: "SHOW"

                status_color: (.18,.70,.32,1)

                position_color: (.60,.45,.95,1)
                position: "A1"

                venue_color: (.55,.35,.80,1)
                venue_code: "TMA"
                day: "Fri"
                date: "Jun 19"
                time: "8:30 PM"

                show: "Summer Walker"
                venue: "T-Mobile Arena"
                address: "3780 S Las Vegas Blvd"
            ShowCard:
                id: show_card_2
                badge: "SHOW"
                badge_color: 0.2,0.45,0.9,1
                stripe_color: 0.2,0.45,0.9,1
                position: "A1"
                position_color: 0.2,0.45,0.9,1

                day: "Fri"
                date: "Jun 19"
                time: "8:30 PM"

                show: "Summer Walker"
                venue: "T-Mobile Arena"
                address: "3780 S Las Vegas Blvd"

            ShowCard:
                id: show_card_3
                badge: "SHOW"
                badge_color: 0.2,0.45,0.9,1
                stripe_color: 0.2,0.45,0.9,1
                position: "A1"
                position_color: 0.2,0.45,0.9,1

                day: "Fri"
                date: "Jun 19"
                time: "8:30 PM"

                show: "Summer Walker"
                venue: "T-Mobile Arena"
                address: "3780 S Las Vegas Blvd"


            



            MDGridLayout:
                cols: 2
                spacing: dp(12)
                #padding : dp(12)
                adaptive_height: True

                StatCard:
                    icon: "currency-usd"
                    value: "8 Days "
                    title: "Until Payday"
                    subtitle: "August 8, 2026"

                    icon_color: app.theme_cls.secondaryColor
                    circle_color:
                        app.theme_cls.secondaryColor[0], \
                        app.theme_cls.secondaryColor[1], \
                        app.theme_cls.secondaryColor[2], \
                        .12
            
                StatCard:
                    icon: "hours-24"
                    value: "10 shows"
                    title: "Have Valid Data"
                    subtitle: "5 Pending"

                    icon_color: app.theme_cls.secondaryColor
                    circle_color:
                        app.theme_cls.secondaryColor[0], \
                        app.theme_cls.secondaryColor[1], \
                        app.theme_cls.secondaryColor[2], \
                        .12

            


            MDCard:
                radius: [20]
                size_hint_y: None
                height: dp(130)

                MDBoxLayout:
                    orientation: "vertical"
                    padding: dp(16)
                    spacing: dp(12)

                    MDBoxLayout:
                        adaptive_height: True

                        MDLabel:
                            text: "June 2026"
                            bold: True

                        MDIconButton:
                            icon: "chevron-left"

                        MDIconButton:
                            icon: "chevron-right"

                    MDGridLayout:
                        cols: 7
                        adaptive_height: True
                        spacing: dp(4)

                        MDLabel:
                            text: "S"
                            halign: "center"

                        MDLabel:
                            text: "M"
                            halign: "center"

                        MDLabel:
                            text: "T"
                            halign: "center"

                        MDLabel:
                            text: "W"
                            halign: "center"

                        MDLabel:
                            text: "T"
                            halign: "center"

                        MDLabel:
                            text: "F"
                            halign: "center"

                        MDLabel:
                            text: "S"
                            halign: "center"



    NavigationBar:
        selected: "home"