#:import dp kivy.metrics.dp

<Badge>:
    size_hint: None, None
    size: dp(84), dp(24)

    canvas.before:
        Color:
            rgba: root.bg_color
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [12]

    MDAnchorLayout:
        anchor_x: "center"
        anchor_y: "center"

        MDIcon:
            icon: root.icon
            opacity: 1 if root.icon else 0

            theme_icon_color: "Custom"
            icon_color: root.fg_color
            font_size: dp(16)

        MDLabel:
            text: root.text
            opacity: 0 if root.icon else 1

            halign: "center"

            theme_text_color: "Custom"
            text_color: root.fg_color

            font_style: "Label"
            role: "small"