#:import dp kivy.metrics.dp

<Badge>:
    size_hint: None, None
    size: dp(84), dp(24)

    canvas.before:
        Color:
            rgba: root.bg_color

        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [12]

    MDLabel:
        text: root.text

        halign: "center"
        valign: "middle"

        adaptive_height: True

        theme_text_color: "Custom"
        text_color: root.fg_color

        font_style: "Label"
        role: "small"

        center: root.center