<NavigationBar>:
    size_hint_y: None
    height: dp(68)

    MDAnchorLayout:
        anchor_x: "center"
        anchor_y: "center"

        MDCard:
            style: "outlined"
            radius: [28]
            theme_bg_color: "Custom"
            md_bg_color: (.9, .91, .918, .9)

            size_hint_x: .94
            height: dp(72)

        MDBoxLayout:

            padding: dp(8)

            NavButton:
                icon: "home"
                text: "Home"
                active: root.selected == "today"

                on_touch_down: app.change_screen("today", "left") if self.collide_point(*args[1].pos) else None

            NavButton:
                icon: "calendar"
                text: "Calendar"
                active: root.selected == "calendar"

                on_touch_down: app.new_login() if self.collide_point(*args[1].pos) else None

            NavButton:
                icon: "history"
                text: "Changes"
                active: root.selected == "changes"

                on_touch_down: app.changes() if self.collide_point(*args[1].pos) else None

            NavButton:
                icon: "hamburger"
                text: "More"
                active: root.selected == "settings"

                on_touch_down: root.goto("settings") if self.collide_point(*args[1].pos) else None