#:import dp kivy.metrics.dp

<ShowCard>:
    style: "filled"
    radius: [18]

    size_hint_y: None
    height: dp(132)

    padding: dp(16)

    MDBoxLayout:
        spacing: dp(16)

        #
        # LEFT SIDE
        #

        MDBoxLayout:
            orientation: "horizontal"
            spacing: dp(16)

            #
            # Accent stripe
            #

            Widget:
                size_hint_x: None
                width: dp(8)

                canvas.before:
                    Color:
                        rgba: root.class_color

                    RoundedRectangle:
                        pos: self.x + dp(1), self.y + dp(2)
                        size: dp(6), self.height - dp(4)
                        radius: [3]

            #
            # Text
            #

            MDBoxLayout:
                orientation: "vertical"

                spacing: dp(4)

                Widget:
                    size_hint_y: None
                    height: dp(10)

                MDLabel:
                    text: root.show
                    adaptive_height: True
                    font_style: "Title"
                    role: "large"

                MDLabel:
                    text: f"{root.day} {root.date} • {root.time}"

                    adaptive_height: True

                    font_style: "Body"
                    role: "large"

                    theme_text_color: "Secondary"

                Widget:
                    size_hint_y: None
                    height: dp(4)

                MDLabel:
                    text: root.venue

                    adaptive_height: True

                    font_style: "Body"
                    role: "medium"

                MDLabel:
                    text: root.address

                    adaptive_height: True

                    font_style: "Body"
                    role: "small"
                    opacity: .25
                    theme_text_color: "Hint"
                    theme_text_color: "Secondary"

                Widget:

        #
        # BADGES
        #

        MDAnchorLayout:
            anchor_x: "right"
            anchor_y: "center"

            size_hint_x: None
            width: dp(92)

            MDBoxLayout:
                orientation: "vertical"

                adaptive_height: True
                spacing: dp(6)

                Badge:
                    text: root.position
                    bg_color: root.position_color

                Badge:
                    text: root.show_class
                    bg_color: root.class_color

                Badge:
                    text: root.status
                    bg_color: root.status_color

                Badge:
                    text: root.venue_code
                    bg_color: root.venue_color