#:import dp kivy.metrics.dp

<ShowCard>:
    style: "filled"
    radius: [18]

    size_hint_y: None
    height: dp(126)

    padding: dp(16)

    MDBoxLayout:
        spacing: dp(12)

        #
        # LEFT CONTENT
        #

        MDBoxLayout:
            orientation: "horizontal"
            spacing: dp(14)

            #
            # class color stripe
            #

            Widget:
                size_hint_x: None
                width: dp(8)

                canvas.before:
                    Color:
                        rgba: root.class_color

                    RoundedRectangle:
                        pos: self.x + dp(2), self.y + dp(2)
                        size: dp(2), self.height - dp(1)
                        radius: [2]

            #
            # text
            #

            MDBoxLayout:
                orientation: "vertical"
                spacing: dp(2)

                Widget:
                    size_hint_y: None
                    height: dp(2)

                MDLabel:
                    text: root.show
                    adaptive_height: True

                    font_style: "Headline"
                    role: "small"

                MDLabel:
                    text: f"{root.day} {root.date} • {root.time}"
                    adaptive_height: True

                    theme_text_color: "Primary"

                    font_style: "Body"
                    role: "large"

                Widget:
                    size_hint_y: None
                    height: dp(6)

                MDLabel:
                    text: root.venue
                    adaptive_height: True

                    font_style: "Body"
                    role: "medium"

                MDLabel:
                    text: root.address
                    adaptive_height: True

                    theme_text_color: "Secondary"

                    font_style: "Body"
                    role: "small"

                Widget:

        #
        # RIGHT BADGES
        #

        MDBoxLayout:
            orientation: "vertical"

            size_hint_x: None
            width: dp(86)

            spacing: dp(4)

            Badge:
                text: root.position
                bg_color: root.position_color

            Badge:
                text: root.show_class
                bg_color: root.class_color

            Badge:
                text: root.status
                bg_color: root.status_color

            Badge:
                text: root.venue_code
                bg_color: root.venue_color

            Widget: