#:import dp kivy.metrics.dp

<StatCard>:
    style: "filled"
    radius: [18]
    size_hint_y: None
    height: dp(99)

    MDBoxLayout:
        orientation: "horizontal"
        padding: dp(6)
        spacing: dp(3)

        FloatLayout:
            size_hint_x: None
            width: dp(56)

            FloatLayout:
                size_hint: None, None
                size: dp(44), dp(44)
                pos_hint: {"center_x": .5, "center_y": .5}

                canvas.before:
                    Color:
                        rgba: root.circle_color
                    Ellipse:
                        pos: self.pos
                        size: self.size

                MDIcon:
                    icon: root.icon
                    pos_hint: {"center_x": .5, "center_y": .5}
                    font_size: dp(22)
                    theme_icon_color: "Custom"
                    icon_color: root.icon_color

        MDBoxLayout:
            orientation: "vertical"

            Widget:

            MDLabel:
                text: root.value
                font_style: "Headline"
                role: "small"
                adaptive_height: True

            MDLabel:
                text: root.title
                theme_text_color: "Secondary"
                adaptive_height: True

            MDLabel:
                text: root.subtitle
                font_style: "Body"
                role: "small"
                adaptive_height: True

            Widget: